name: "sonar js"

on:
  workflow_call:
    inputs:
      SONAR_PROJECT_NAME:
        required: true
        type: string
      

    secrets:      
      GIT_TOKEN:
        required: true
      SONAR_TOKEN: 
        required: true
      SONAR_URL:
        required: true  


jobs:
  sonar:
    name: "sonar-build"     
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create sonar.properties file
        run: echo 'sonar.projectKey=${{ inputs.SONAR_PROJECT_NAME }}' >sonar-project.properties
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}